# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.banka.example.com:
  peer1.banka.example.com:
  peer0.bankb.example.com:
  peer1.bankb.example.com:

networks:
  bankchain:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-banka
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.banka.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4c23161d9e5bc66ceb0c4ad4547d2295ba42a0d8a5d25e8c1fbc429f1980f695_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.banka.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4c23161d9e5bc66ceb0c4ad4547d2295ba42a0d8a5d25e8c1fbc429f1980f695_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/banka.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerbanka
    networks:
      - bankchain

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bankb
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bankb.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ea9e8938d515014e18214f2e91c71b67aec806e18334bf3af3decac173e96441_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bankb.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ea9e8938d515014e18214f2e91c71b67aec806e18334bf3af3decac173e96441_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bankb.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerbankb
    networks:
      - bankchain

  orderer.example.com:
    extends:
      file:   base/docker-compose-base-bankchain.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - bankchain

  peer0.banka.example.com:
    container_name: peer0.banka.example.com
    extends:
      file:  base/docker-compose-base-bankchain.yaml
      service: peer0.banka.example.com
    networks:
      - bankchain

  peer1.banka.example.com:
    container_name: peer1.banka.example.com
    extends:
      file:  base/docker-compose-base-bankchain.yaml
      service: peer1.banka.example.com
    networks:
      - bankchain

  peer0.bankb.example.com:
    container_name: peer0.bankb.example.com
    extends:
      file:  base/docker-compose-base-bankchain.yaml
      service: peer0.bankb.example.com
    networks:
      - bankchain

  peer1.bankb.example.com:
    container_name: peer1.bankb.example.com
    extends:
      file:  base/docker-compose-base-bankchain.yaml
      service: peer1.bankb.example.com
    networks:
      - bankchain
